export default function Insights() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8 text-white">
      <h1 className="text-2xl font-bold mb-1">Insights</h1>
      <p className="text-zinc-400 text-sm mb-8">
        Sleep quality vs. medication timeline, ML risk flag, and AI-generated summaries — coming in a later sprint.
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-zinc-900 border border-zinc-700 rounded-xl p-5">
          <h2 className="font-semibold mb-2">Medication Timeline</h2>
          <p className="text-zinc-400 text-sm">
            Sleep quality overlaid with medication start / stop events.
          </p>
          <p className="text-xs text-zinc-600 mt-3">Planned — Sprint 4</p>
        </div>

        <div className="bg-zinc-900 border border-zinc-700 rounded-xl p-5">
          <h2 className="font-semibold mb-2">Risk Flag</h2>
          <p className="text-zinc-400 text-sm">
            ML model output indicating elevated risk of poor sleep quality.
          </p>
          <p className="text-xs text-zinc-600 mt-3">Planned — Sprint 4</p>
        </div>

        <div className="bg-zinc-900 border border-zinc-700 rounded-xl p-5">
          <h2 className="font-semibold mb-2">AI Summary</h2>
          <p className="text-zinc-400 text-sm">
            Plain-language summary of sleep trends generated by Flan-T5.
          </p>
          <p className="text-xs text-zinc-600 mt-3">Planned — Sprint 5</p>
        </div>
      </div>
    </div>
  );
}
